CREATE TABLE DEPARTMENT (
    Dname           VARCHAR(50)  NOT NULL,
    Dnumber         INT          NOT NULL,
    Mgr_ssn         CHAR(9)      NULL,        -- FK adicionada depois
    Mgr_start_date  DATE         NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (Dnumber),
    CONSTRAINT UQ_DEPARTMENT_Dname UNIQUE (Dname)
);
CREATE TABLE EMPLOYEE (
	Fname			VARCHAR(30)		NOT NULL,
	Minit			CHAR(9)			NULL,
	Lname			VARCHAR(30)		NOT NULL,
	Ssn				CHAR(9)			NOT NULL,
	Bdate			DATE			NULL,
	Address_		VARCHAR(100)	NULL,
	Sex				CHAR(1)			NULL,
	Salary			DECIMAL(12,2)	NULL,
	Super_ssn		CHAR(9)			NULL,
	Dno				INT				NULL,

	CONSTRAINT PK_EMPLOYEE PRIMARY KEY (Ssn),
    CONSTRAINT CK_EMPLOYEE_Sex CHECK (Sex IN ('M','F')),
    CONSTRAINT CK_EMPLOYEE_Salary CHECK (Salary IS NULL OR Salary > 0)
);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_DEPT
	FOREIGN KEY(Dno) REFERENCES DEPARTMENT(Dnumber);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_SUPER
	FOREIGN KEY(Super_ssn) REFERENCES EMPLOYEE(Ssn);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_MGR
	FOREIGN KEY(Mgr_ssn) REFERENCES EMPLOYEE(Ssn);
	
CREATE TABLE DEPT_LOCATIONS (
	Dnumber		INT				NOT NULL,
	Dlocation	VARCHAR(50)		NOT NULL,
	CONSTRAINT PK_DEPT_LOCATION PRIMARY KEY(Dnumber, Dlocation)
);

ALTER TABLE DEPT_LOCATION
ADD CONSTRAINT FK_DEPT_LOCATION_DEPT
	FOREIGN KEY(Dnumber) REFERENCES DEPARTMENT(Dnumber);

CREATE TABLE PROJECT (
	Pname		VARCHAR(30)		NOT NULL,
	Pnumber		INT				NOT NULL,
	Plocation	VARCHAR(50)		NOT NULL,
	Dnum		INT
	CONSTRAINT PK_PROJECT PRIMARY KEY(Pnumber),
	CONSTRAINT UQ_PROJECT_Pname UNIQUE (Pname) -- Garantir que o nome é unico 
);

ALTER TABLE PROJECT
ADD CONSTRAINT FK_PROJECT_DEPT
	FOREIGN KEY(Dnum) REFERENCES DEPARTMENT(Dnumber);


CREATE TABLE WORKS_ON (
    Essn   CHAR(9)  NOT NULL,
    Pno    INT      NOT NULL,
    Hours  DECIMAL(4,1) NOT NULL,
    CONSTRAINT PK_WORKS_ON PRIMARY KEY (Essn, Pno),
    CONSTRAINT FK_WORKS_ON_EMP FOREIGN KEY (Essn)
        REFERENCES EMPLOYEE(Ssn),
    CONSTRAINT FK_WORKS_ON_PROJ FOREIGN KEY (Pno)
        REFERENCES PROJECT(Pnumber),
    CONSTRAINT CK_WORKS_ON_Hours CHECK (Hours >= 0 AND Hours <= 56) -- limite semanal razoável
);

CREATE TABLE DEPENDENT (
    Essn            CHAR(9)     NOT NULL,
    Dependent_name  VARCHAR(50) NOT NULL,
    Sex             CHAR(1)     NULL,
    Bdate           DATE        NULL,
    Relationship    VARCHAR(25) NOT NULL,
    CONSTRAINT PK_DEPENDENT PRIMARY KEY (Essn, Dependent_name),
    CONSTRAINT FK_DEPENDENT_EMP FOREIGN KEY (Essn)
        REFERENCES EMPLOYEE(Ssn),
    CONSTRAINT CK_DEPENDENT_Sex CHECK (Sex IN ('M','F'))
);